version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: skin_analysis
      MYSQL_ROOT_PASSWORD: "UEsQr357!"
      MYSQL_USER: "t.handa"
      MYSQL_PASSWORD: "UEsQr357!"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
